# Generated by Django 5.2 on 2025-05-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.PositiveIntegerField(default=1, help_text='Score for the quiz'),
        ),
    ]
