# Generated by Django 5.2 on 2025-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('time_estimate', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
