# Generated by Django 5.2 on 2025-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0002_alter_exercise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
