# Generated by Django 5.2 on 2025-04-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_code', models.TextField(help_text='Starting code template for the exercise')),
                ('solution_code', models.TextField(help_text='Solution code for the exercise')),
                ('test_cases', models.JSONField(default=list, help_text='List of test cases to validate the solution')),
                ('hints', models.JSONField(default=list, help_text='List of hints for the exercise')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12)),
                ('order', models.PositiveIntegerField(default=1, help_text="Order of the exercise in the snippet's exercise list")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_exercises', to='snippet.codesnippet')),
            ],
            options={
                'ordering': ['snippet', 'order'],
                'unique_together': {('snippet', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('running', 'Running')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='snippet.practiceexercise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
