# Generated by Django 5.2 on 2025-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_practiceexercise_codeexecution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practiceexercise',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='practiceexercise',
            name='snippet',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CodeExecution',
        ),
        migrations.DeleteModel(
            name='PracticeExercise',
        ),
    ]
