# Generated by Django 5.2 on 2025-04-29 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_alter_practiceexercise_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='saved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
