# Generated by Django 5.2 on 2025-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_codesnippet_saved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='saved_at',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
