# Generated by Django 5.2 on 2025-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorSolution',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('solution', models.TextField()),
                ('explanation', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6)),
                ('votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-votes', '-created_at'],
            },
        ),
    ]
