# Generated by Django 5.2 on 2025-04-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0009_errorsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorsolution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
