# Generated by Django 5.2 on 2025-04-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0010_alter_errorsolution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorsolution',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
