# Generated by Django 5.2 on 2025-04-30 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0013_usersolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersolution',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'User Solution', 'verbose_name_plural': 'User Solutions'},
        ),
        migrations.AddField(
            model_name='usersolution',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersolution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_solutions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SaveSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('runtime', models.FloatField(default=0)),
                ('memory_usage', models.IntegerField(default=0)),
                ('output', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_solutions', to='snippet.errorsolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_solutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Solution',
                'verbose_name_plural': 'Saved Solutions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
