# Generated by Django 5.2 on 2025-09-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0014_alter_usersolution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='snippet',
            field=models.JSONField(default=list),
        ),
    ]
