# Generated by Django 5.2 on 2025-04-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
