# Generated by Django 5.2 on 2025-04-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_codesnippet_difficulty_level_codesnippet_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
